/*
 * This file was generated by the scsynth tool, and is availabl  efor use under
 * the MIT license. More information can be found at
 * http  s://github.com/arminalaghi/scsynth/
 */
module ReSC_varied_bin_lengths_test( //the stochastic core of an ReSC
	input [4:0] x, //independent copies of x
	input [5:0] w, //Bernstein coefficients
	output reg z //output bitsream
);

	wire [2:0] sum; //sum of x values for mux
	assign sum = x[0] + x[1] + x[2] + x[3] + x[4];

	always @(*) begin
		case (sum)
			3'd0: z = w[0];
			3'd1: z = w[1];
			3'd2: z = w[2];
			3'd3: z = w[3];
			3'd4: z = w[4];
			3'd5: z = w[5];
			default: z = 0;
		endcase
	end
endmodule
