/*
 * This file was generated by the scsynth tool, and is availabl  efor use under
 * the MIT license. More information can be found at
 * http  s://github.com/arminalaghi/scsynth/
 */
module ReSC_test_varied_bin_lengths_test(); //a testbench for an ReSC module
	reg [5:0] x_bin; //binary value of input
	reg start;
	wire done;
	wire [9:0] z_bin; //binary value of output
	reg [9:0] expected_z; //expected output

	reg clk;
	reg reset;

	ReSC_wrapper_varied_bin_lengths_test ReSC (
		.x_bin (x_bin),
		.start (start),
		.done (done),
		.z_bin (z_bin),
		.clk (clk),
		.reset (reset)
	);

	always begin
		#1 clk <= ~clk;
	end

	initial begin
		clk = 0;
		reset = 1;
		#1 reset = 0;
		start = 1;

		#2 x_bin = 6'd56;
		expected_z = 10'd725;
		start = 0;

		#2054 x_bin = 6'd12;
		expected_z = 10'd200;
		start = 0;

		#2054 x_bin = 6'd14;
		expected_z = 10'd220;
		start = 0;

		#2054 x_bin = 6'd42;
		expected_z = 10'd525;
		start = 0;

		#2054 x_bin = 6'd45;
		expected_z = 10'd565;
		start = 0;

		#2054 x_bin = 6'd37;
		expected_z = 10'd460;
		start = 0;

		#2054 x_bin = 6'd21;
		expected_z = 10'd275;
		start = 0;

		#2054 x_bin = 6'd7;
		expected_z = 10'd155;
		start = 0;

		#2054 x_bin = 6'd44;
		expected_z = 10'd555;
		start = 0;

		#2054 x_bin = 6'd29;
		expected_z = 10'd365;
		start = 0;

		#2054 x_bin = 6'd10;
		expected_z = 10'd186;
		start = 0;

		#2068 $stop;
	end

	always @(posedge done) begin
		$display("x: %b, z: %b, expected_z: %b",x_bin, z_bin, expected_z);
		start = 1;
	end
endmodule
