/*
 * This file was generated by the scsynth tool, and is availablefor use under
 * the MIT license. More information can be found at
 * https://github.com/arminalaghi/scsynth/
 */
module ReSC_test_paper_example(); //a testbench for an ReSC module
	reg [9:0] x_bin; //binary value of input
	reg start;
	wire done;
	wire [9:0] z_bin; //binary value of output
	reg [9:0] expected_z; //expected output

	reg clk;
	reg reset;

	ReSC_wrapper_paper_example ReSC (
		.x_bin (x_bin),
		.start (start),
		.done (done),
		.z_bin (z_bin),
		.clk (clk),
		.reset (reset)
	);

	always begin
		#1 clk <= ~clk;
	end

	initial begin
		clk = 0;
		reset = 1;
		#1 reset = 0;
		start = 1;

		#2 x_bin = 10'd39;
		expected_z = 10'd297;
		start = 0;

		#2054 x_bin = 10'd866;
		expected_z = 10'd631;
		start = 0;

		#2054 x_bin = 10'd319;
		expected_z = 10'd467;
		start = 0;

		#2054 x_bin = 10'd208;
		expected_z = 10'd421;
		start = 0;

		#2054 x_bin = 10'd924;
		expected_z = 10'd672;
		start = 0;

		#2054 x_bin = 10'd149;
		expected_z = 10'd387;
		start = 0;

		#2054 x_bin = 10'd356;
		expected_z = 10'd478;
		start = 0;

		#2054 x_bin = 10'd431;
		expected_z = 10'd496;
		start = 0;

		#2054 x_bin = 10'd770;
		expected_z = 10'd581;
		start = 0;

		#2054 x_bin = 10'd969;
		expected_z = 10'd712;
		start = 0;

		#2054 x_bin = 10'd312;
		expected_z = 10'd465;
		start = 0;

		#2068 $stop;
	end

	always @(posedge done) begin
		$display("x: %b, z: %b, expected_z: %b", x_bin, z_bin, expected_z);
		start = 1;
	end
endmodule
