%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Copyright (C) 2016 N. Eamon Gaffney
%%
%% This program is free software; you can resdistribute and/or modify it under
%% the terms of the MIT license, a copy of which should have been included with
%% this program at https://github.com/arminalaghi/scsynth
%%
%% References:
%% Qian, W., Li, X., Riedel, M. D., Bazargan, K., & Lilja, D. J. (2011). An
%% Architecture for Fault-Tolerant Computation with Stochastic Logic. IEEE
%% Transactions on Computers IEEE Trans. Comput., 60(1), 93-105.
%% doi:10.1109/tc.2010.202
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function VerilogCoreReSCGenerator (degree, moduleName)

  %Generates an ReSC module in verilog whose inputs and outputs
  %remain in stochastic format
  
  %Parameters:
  % degree    : the degree of the Bernstein polynomial
  % moduleName: the name of the verilog module
  
  fileName = sprintf('%s.v', moduleName);
  header = "/*\n * This file was generated by the scsynth tool, and is availabl\
efor use under\n * the MIT license. More information can be found at\n * https:\
//github.com/arminalaghi/scsynth/\n */\n"
  
  fp = fopen(fileName, 'w');
  
  fprintf(fp, header);
  fprintf(fp, 'module %s( //the stochastic core of an ReSC\n', moduleName);
	fprintf(fp, '\tinput [%d:0] x, //independent copies of x\n', degree - 1);
  fprintf(fp, '\tinput [%d:0] w, //Bernstein coefficients\n', degree);
  fprintf(fp, '\toutput reg z //output bitsream\n);\n\n');

  bits = ceil(log2(degree));
	fprintf(fp, '\twire [%d:0] sum; //sum of x values for mux\n', bits - 1); 
	fprintf(fp, '\tassign sum = x[0]');
  for i=1:degree - 1
    fprintf(fp, ' + x[%d]', i);
  end
  fprintf(fp, ';\n\n');
  
	fprintf(fp, '\talways @(*) begin\n');
	fprintf(fp, '\t\tcase (sum)\n');
  for i=0:degree
    fprintf(fp, "\t\t\t%d'd%d: z = w[%d];\n", bits, i, i);
  end
  fprintf(fp, '\t\t\tdefault: z = 0;\n');
	fprintf(fp, '\t\tendcase\n');
	fprintf(fp, '\tend\n');
  fprintf(fp, 'endmodule\n');
  
  fclose(fp);
end
